---
- hosts: all
  become: yes
  tasks:
  - name: i want to intall webserver on ubuntu node server
    apt:
       name: apache2
       state: present

  - name: i want start the service
    service: 
      name: apache2
      state: restarted